apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  type: NodePort
  ports:
    - name: http
      port: 8081
      nodePort: 30001


------

apiVersion: app/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: service
          image: ivashova2002/user-service
          ports:
            - name: http
              containerPort: 8081

---